# Generated by Django 4.0.3 on 2022-03-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='call_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='library_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='town',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(null=True),
        ),
    ]
