# Generated by Django 4.0.3 on 2022-03-27 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_library_address_alter_library_call_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
