# Generated by Django 4.0.3 on 2022-03-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialrating',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
