# Generated by Django 4.0.3 on 2022-03-27 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_socialrating_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialrating',
            old_name='user_id',
            new_name='userr_id',
        ),
    ]
