# Generated by Django 4.0.3 on 2022-03-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_rename_user_id_socialrating_userr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialrating',
            name='userr_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
