# Generated by Django 4.0.3 on 2022-03-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_socialrating_userr_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialrating',
            name='userr_id',
        ),
        migrations.AddField(
            model_name='socialrating',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
