# Generated by Django 4.0.3 on 2022-03-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_remove_socialrating_userr_id_socialrating_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialrating',
            name='user_id',
            field=models.FloatField(default=0),
        ),
    ]
