# Generated by Django 4.0.3 on 2022-03-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_socialrating_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='socialrating',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
